services:
  accounts:
    image: niladrdev/accounts:v1
    container_name: Accounts-container-microservices-v1
    ports:
      - "4000:8080"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
        - niladri
  loans:
    image: niladrdev/loans:v1
    container_name: Loans-container-microservices-v1
    ports:
      - "5000:9005"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
        - niladri
  cards:
    image: niladrdev/cards:v1
    container_name: Cards-container-microservices-v1
    ports:
      - "6000:9000"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
        - niladri
networks:
  niladri:
    driver: bridge
