spring:
  application:
    name: configserver
  profiles:
    #    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/niladriSen007/microservice-centralize-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "HGFGHF4F34H5F3H5F35H3G4F53HG4F5HG3F45HG34F53HG45F34GH5F3H5F3HG45"
server:
  port: 8071

