spring:
  application:
    name: configserver
  profiles:
    #    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/niladriSen007/microservice-centralize-configuration.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071

